version: '3'
services:
  api:
    container_name: workchain-api
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
  redis:
    container_name: workchain-redis
    image: "redis:alpine"
    expose:
      - 6379
